### PR TITLE
adapt man to new command lines

### PR DESCRIPTION
**Pull request by ejannett**

### CODE REVIEW

**Comment by wbora** [comment]
The optional arguments should be using '[' not '('

**Comment by ejannett** [comment]
Hi,

These option are not optional. 

for create-pool.  you must either specify a disk or a netfshopst and path couple of options  

How Am I suppose to expose this ?

**Comment by wbora** [comment]
In general, curly brackets are used to indicate there are multiple options of which any one of them need to be supplied, i.e.: .B {-d
.I DEVICE
.B  | -N
.I HOST
.B -p
.I PATH}

**Comment by ejannett** [comment]
I'v applied the proposed syntax and pushed the changes

**Pull request merged**
